force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/DaysLeftToClose__c.field-meta.xml
<CustomField>
    <fullName>DaysLeftToClose__c</fullName>
    <description>Indicates how many days is left to StartDate</description>
    <formula>StartDate__c - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysLeftToClose</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/DaysOpen__c.field-meta.xml
<CustomField>
    <fullName>DaysOpen__c</fullName>
    <description>Indicates how many days the vacancy is open</description>
    <formula>NOW() - CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysOpen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Recruiters only</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <infoMessage>Recruiters only</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VacanciesManagementController.cls
public with sharing class VacanciesManagementController {
    
    public List <Vacancy__c> vacancyList {get; set;}
    public String customFilterByResponsible {get; set;}
    
    public VacanciesManagementController () {
        if(customFilterByResponsible == null) {
            customFilterByResponsible = 'unselected';
        }
        updateVacancyList();
    }
    
    public void updateVacancyList() {
        if (customFilterByResponsible == 'all') {
            this.vacancyList = [
                SELECT Id, Title__c, Level__c, DaysOpen__c, DaysLeftToClose__c, Responsible__c 
                FROM Vacancy__c 
                ORDER BY StartDate__c
            ];
        } else if(customFilterByResponsible == 'selected') {
            this.vacancyList = [
                SELECT Id, Title__c, Level__c, DaysOpen__c, DaysLeftToClose__c, Responsible__c 
                FROM Vacancy__c 
                WHERE Responsible__c != NULL
                ORDER BY StartDate__c
            ];
        } else if (customFilterByResponsible == 'unselected') {
            this.vacancyList = [
                SELECT Id, Title__c, Level__c, DaysOpen__c, DaysLeftToClose__c, Responsible__c 
                FROM Vacancy__c 
                WHERE Responsible__c = NULL
                ORDER BY StartDate__c
            ];
        }
    }
    
    public void showAll() {
        this.customFilterByResponsible = 'all';
        updateVacancyList();
    }
    public void showSelected() {
        this.customFilterByResponsible = 'selected';
        updateVacancyList();
    }
    public void showUnselected() {
        this.customFilterByResponsible = 'unselected';
        updateVacancyList();
    }
    
    public void saveList() {
        upsert vacancyList;
        updateVacancyList();
    }
}