force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Candidate&#39;s status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_to_Vacancy__c/Candidate_to_Vacancy__c.object-meta.xml
<CustomObject>
    <description>Junction table</description>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>C2V-{0000}</displayFormat>
        <label>Candidate to Vacancy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_to_Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Candidate has to be Validated by HR</errorMessage>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Candidates_to_Vacancies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate_to_Vacancy__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Vacancy has to be In-Process</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates_to_Vacancies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Validated candidates only available</errorMessage>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <infoMessage>Validated candidates only</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VacanciesController.cls
public with sharing class VacanciesController {

    public String customFilterByStatus { get; set; }
    @TestVisible public List <wrapVacancy> vacancies { get; set; }

    @TestVisible public class wrapVacancy {
        public Vacancy__c vacancy { get; set; }
        public Boolean checked { get; set; }
        @TestVisible public List <wrapConnection> connections { get; set; }

        public wrapVacancy(Vacancy__c vacancy, List <Candidate_to_Vacancy__c> connections) {
            this.vacancy = vacancy;
            this.checked = false;
            this.connections = new List <wrapConnection>();
            for (Candidate_to_Vacancy__c connection : connections) {
                this.connections.add(new wrapConnection(connection));
            }
        }

        public Candidate__c prepareApprove() {
            Candidate__c candidateToApprove;
            for (wrapConnection c : this.connections) {
                if (c.checked) {
                    this.vacancy.Candidate__c = c.connection.Candidate__c;
                    this.vacancy.Status__c = 'Closed';
                    candidateToApprove = c.connection.Candidate__r;
                    candidateToApprove.Status__c = 'Hired';
                }
            }
            return candidateToApprove;
        }
    }

    @TestVisible public class wrapConnection {
        public Candidate_to_Vacancy__c connection { get; set; }
        public Boolean checked { get; set; }

        public wrapConnection(Candidate_to_Vacancy__c connection) {
            this.connection = connection;
            this.checked = false;
        }
    }
    
    public VacanciesController() {
        this.customFilterByStatus = 'In-Process';
        this.vacancies = updateVacancies();
    }

    public List <wrapVacancy> updateVacancies() {
        List <wrapVacancy> result = new List <wrapVacancy>();

        List <Vacancy__c> vacancies = [
                SELECT Id,
                        Title__c,
                        Status__c,
                        Candidate__c,
                        Candidate__r.FirstName__c,
                        Candidate__r.LastName__c, (
                        SELECT Id,
                                Candidate__r.FirstName__c,
                                Candidate__r.LastName__c,
                                Candidate__r.Email__c,
                                Candidate__c
                        FROM Candidates_to_Vacancies__r
                )
                FROM Vacancy__c
                WHERE Status__c = :customFilterByStatus
        ];

        for (Vacancy__c connection : vacancies) {
            result.add(new wrapVacancy(connection, connection.Candidates_to_Vacancies__r));
        }
        return result;
    }

    /**
     * Clear bad junctions
     */
    private void clearJunctions() {
        List<Candidate_to_Vacancy__c> connections = [
                SELECT Id
                FROM Candidate_to_Vacancy__c
                WHERE Vacancy__r.Status__c = 'Closed'
                OR Vacancy__r.Status__c = 'Cancelled'
                OR Candidate__r.Status__c = 'Hired'
        ];
        delete connections;
    }

    public void showNew() {
        this.customFilterByStatus = 'New';
        this.vacancies = updateVacancies();
    }

    public void showInProcess() {
        this.customFilterByStatus = 'In-Process';
        this.vacancies = updateVacancies();
    }

    public void showCancelled() {
        this.customFilterByStatus = 'Cancelled';
        this.vacancies = updateVacancies();
    }

    public void showClosed() {
        this.customFilterByStatus = 'Closed';
        this.vacancies = updateVacancies();
    }

    public void cancelSelected() {
        List<Vacancy__c> cancelVacancyList = new List<Vacancy__c>();
        if(validateCancelled()) {
            for(wrapVacancy v: this.vacancies) {
                if(v.checked) {
                    v.vacancy.Status__c = 'Cancelled';
                    cancelVacancyList.add(v.vacancy);
                }
            }
            update cancelVacancyList;
            this.clearJunctions();
            this.vacancies = updateVacancies();
        }
    }

    public void approveSelected() {
        List<Vacancy__c> updateVacancyList = new List<Vacancy__c>();
        List<Candidate__c> updateCandidateList = new List<Candidate__c>();
        if (validateApproved()) {
            for (wrapVacancy v : this.vacancies) {
                Candidate__c candidateToApprove = v.prepareApprove();
                if (candidateToApprove != null) {
                    updateVacancyList.add(v.vacancy);
                    updateCandidateList.add(candidateToApprove);
                }
            }
            update updateVacancyList;
            update updateCandidateList;
            this.clearJunctions();
            this.vacancies = updateVacancies();
        }
    }

    public void removeSelected() {
        if (validateRemoved()) {
            List<Candidate_to_Vacancy__c> removeList = new List<Candidate_to_Vacancy__c>();
            for (wrapVacancy v : this.vacancies) {
                for (wrapConnection c : v.connections) {
                    if (c.checked) {
                        removeList.add(c.connection);
                    }
                }
            }
            delete removeList;
            this.vacancies = updateVacancies();
        }
    }

    private Boolean validateCancelled() {
        Boolean cancelValidated = true;
        Integer counter = 0;
        for (wrapVacancy v: this.vacancies) {
            if(v.checked) {
                counter++;
            }
        }
        if(counter < 1) {
            cancelValidated = false;
            ApexPages.addMessage(
                    new ApexPages.Message(
                            ApexPages.Severity.WARNING,
                            'Nothing to cancel'
                    )
            );
        }
        return cancelValidated;
    }

    private Boolean validateApproved() {
        Boolean approveValidated = true;
        Integer vacancyCounter = 0;
        List<Id> candidatesIds = new List<Id>();
        for (wrapVacancy v : vacancies) {
            Integer connectionCounter = 0;
            for (wrapConnection c : v.connections) {
                if (c.checked) {
                    vacancyCounter++;
                    connectionCounter++;
                    if (candidatesIds.contains(c.connection.Candidate__c)) {
                        approveValidated = false;
                        ApexPages.addMessage(
                                new ApexPages.Message(
                                        ApexPages.Severity.ERROR,
                                        'One Candidate can be approved only for one Vacancy'
                                )
                        );
                    } else {
                        candidatesIds.add(c.connection.Candidate__c);
                    }
                }
                if (connectionCounter > 1) {
                    approveValidated = false;
                    ApexPages.addMessage(
                            new ApexPages.Message(
                                    ApexPages.Severity.ERROR,
                                    'Only one candidate per vacancy can be approved'
                            )
                    );
                }
            }
        }
        if (vacancyCounter < 1) {
            approveValidated = false;
            ApexPages.addMessage(
                    new ApexPages.Message(
                            ApexPages.Severity.WARNING,
                            'Nothing to approve'
                    )
            );
        }

        return approveValidated;
    }

    private Boolean validateRemoved() {
        Boolean removeValidated = true;
        Integer counter = 0;
        for (wrapVacancy v : vacancies) {
            for (wrapConnection c : v.connections) {
                if (c.checked) {
                    counter++;
                }
            }
        }
        if (counter < 1) {
            removeValidated = false;
            ApexPages.addMessage(
                    new ApexPages.Message(
                            ApexPages.Severity.WARNING,
                            'Nothing to remove'
                    )
            );
        }
        return removeValidated;
    }
}