force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Candidate&#39;s status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_to_Vacancy__c/Candidate_to_Vacancy__c.object-meta.xml
<CustomObject>
    <description>Junction table</description>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>C2V-{0000}</displayFormat>
        <label>Candidate to Vacancy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_to_Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Candidate has to be Validated by HR</errorMessage>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Candidates_to_Vacancies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate_to_Vacancy__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Vacancy has to be In-Process</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates_to_Vacancies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Validated candidates only available</errorMessage>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <infoMessage>Validated candidates only</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VacanciesAsignmentController.cls
public with sharing class VacanciesAsignmentController {
    
    public Candidate__c currentCandidate { get; set; }
    public Candidate_to_Vacancy__c newRelation { get; set; }
    @TestVisible public List<wrapVacancyAssignment> connections { get; set; }
    
    public VacanciesAsignmentController(ApexPages.StandardController controller) {
        List<String> fields = new List<String>{'Status__c'};
            if (!Test.isRunningTest()) {
                controller.addFields(fields);
            }
        this.currentCandidate = (Candidate__c) controller.getRecord();
        this.createNewRelation();
        this.updateConnections();
    }
    
    private void updateConnections() {
        List<Candidate_to_Vacancy__c> connections = [
            SELECT Vacancy__r.Id,
            Vacancy__r.Title__c
            FROM Candidate_to_Vacancy__c
            WHERE Candidate__r.Id = :this.currentCandidate.Id
        ];
        this.connections = new List<wrapVacancyAssignment>();
        this.connections.clear();
        for(Candidate_to_Vacancy__c c: connections) {
            this.connections.add(new wrapVacancyAssignment(c));
        }
    }
    
    private void createNewRelation() {
        if (this.newRelation == null) {
            this.newRelation = new Candidate_to_Vacancy__c();
            this.newRelation.Candidate__c = this.currentCandidate.Id;
        }
    }
    
    public void removeConnections() {
        if(this.validateRemovement()) {
            List<Candidate_to_Vacancy__c> delList = new List<Candidate_to_Vacancy__c>();
            for(wrapVacancyAssignment c: this.connections) {
                if(c.checked) {
                    delList.add(c.connection);
                }
            }
            delete delList;
            this.updateConnections();
        }
    }
    
    public void asignVacancy() {
        if (this.validateAssignment()) {
            upsert this.newRelation;
        }
        this.newRelation = null;
        this.createNewRelation();
        this.updateConnections();
    }
    
    private Boolean validateRemovement() {
        for(wrapVacancyAssignment c: this.connections) {
            if(c.checked) {
                return true;
            }
        }
        ApexPages.addMessage(
            new ApexPages.Message(
                ApexPages.Severity.WARNING,
                'Nothing to remove'
            )
        );
        return false;
    }
    
    private Boolean validateAssignment() {
        Boolean validated = true;
        List <Candidate_to_Vacancy__c> checkExisting = [
            SELECT Id
            FROM Candidate_to_Vacancy__c
            WHERE Vacancy__c = :this.newRelation.Vacancy__c
            AND Candidate__c = :this.newRelation.Candidate__c
        ];
        if (checkExisting.size() > 0) {
            validated = false;
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'This candidate is already asigned'
                )
            );
        }
        
        return validated;
    }
    
    @TestVisible public class wrapVacancyAssignment {
        public Candidate_to_Vacancy__c connection { get; set; }
        public Boolean checked { get; set; }
        
        public wrapVacancyAssignment(Candidate_to_Vacancy__c connection) {
            this.connection = connection;
            this.checked = false;
        }
    }
}